### ISSUE TITLE
Supply zone type?

### ISSUE THREAD

**Issue by rmcmullanLB** [rmick/LTTO_Library#3]
Thanks for the great library.  Apologies if this is just me not understanding things.  When I was trying to learn the sendZoneBeacon function, the Medic Station example (https://github.com/rmick/LTTO_Library/blob/master/examples/MedicStation/MedicStation.ino), shows the syntax:
ltto.sendZoneBeacon(SUPPLY_ZONE, teamID); 
But when I look at the SendIR.cpp, I get the impression that it wants the byte "11" instead of SUPPLY_ZONE.  
HashDefines.h has #define  SUPPLY_ZONE  'c'
Is 'c' the same as the byte 11?

**Comment by rmick** [comment]
Yes you are right, that code will never work.

I mistakenly edited these recently, without looking back over all the code to see what it might break. Stupid me!

All fixed now, reverted back to the original settings.

**Comment by rmick** [comment]
Well spotted. That is my mistake. I recently added some new functionality and did some other clean up whilst I was there. Obviously I was not really concentrating as I made a couple of silly mistakes. Probably due to not looking at us for almost 3 years and forgetting how I did it. 
I have just reverted back to the old version. It should be ready for download now. 

    	
    	

    	Get Outlook for iOS
    
  



On Sun, Jun 2, 2019 at 2:24 AM +1000, "rmcmullanLB" <notifications@github.com> wrote:












Thanks for the great library.  Apologies if this is just me not understanding things.  When I was trying to learn the sendZoneBeacon function, the Medic Station example (https://github.com/rmick/LTTO_Library/blob/master/examples/MedicStation/MedicStation.ino), shows the syntax:

ltto.sendZoneBeacon(SUPPLY_ZONE, teamID);

But when I look at the SendIR.cpp, I get the impression that it wants the byte "11" instead of SUPPLY_ZONE.

HashDefines.h has #define  SUPPLY_ZONE  'c'

Is 'c' the same as the byte 11?
